name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  textgrabber2:
    name: TextGrabber2
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v4
      - name: Build TextGrabber2
        run: |
          xcodebuild build -scheme TextGrabber2 -destination 'platform=macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
